services:
  web:
    build: .
    container_name: flask_app
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: flask_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: prix
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    image: node:20
    container_name: flask_frontend
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
      - ./app/static:/app/app/static
    command: sh -c "npm install && npx gulp watch"

volumes:
  mysql_data:
